# This feature sets up network monitoring

automation: !include_dir_merge_list automations

# Speedtest.net regular monitoring
speedtestdotnet:
  manual: true

# UptimeRobot sensors
binary_sensor:
  - platform: uptimerobot
    api_key: ur371912-552335feef248bdf2ed51d91 # Ready-only api key
    entity_namespace: uptime_robot
    scan_interval: 300
