# This feature sets up network monitoring

automation: !include_dir_merge_list automations

# UptimeRobot sensors
binary_sensor:
  - platform: uptimerobot
    api_key: !secret uptimerobot_api_key
    entity_namespace: uptime_robot
    scan_interval: 300
