binary_sensor:
  - platform: "rest"
    name: "Vaccin for 1994"
    resource: "https://user-api.coronatest.nl/vaccinatie/programma/bepaalbaar/1994/NEE/NEE"
    method: "GET"
    # Response is a JSON object with:
    # - success: boolean
    value_template: "{{ value_json.success }}"
    # Update every 15 minutes
    scan_interval: 900
    # Force update so that I know that this is still updating correctly
    force_update: true
    device_class: lock
