- id: '1578751685651'
  alias: Turn off the lights when I leave home
  description: ''
  trigger:
  - entity_id: person.thijs
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - device_id: 436065d78a7b4f0499a2f1c67ca366c7
    domain: light
    entity_id: light.dining_hall
    type: turn_off
  - device_id: 29ba070d706943209a9f3c3b417c0e5c
    domain: light
    entity_id: light.kitchen_closet
    type: turn_off
  - device_id: 0f3f6c87a99148389d0170e8cbdfd9cd
    domain: light
    entity_id: light.living_room_tv
    type: turn_off
  - device_id: 602356ce59a447cd9525dbf02d76c26e
    domain: light
    entity_id: light.dining_long_wall
    type: turn_off
  - device_id: 0cd4097759e6440c81b702ae8bce5576
    domain: light
    entity_id: light.living_room_couch
    type: turn_off
  - device_id: 68f5277ce4ba4382b6bf78179fe7695f
    domain: light
    entity_id: light.kitchen_cooking
    type: turn_off
  - device_id: adb2ea00690b4e7888810888ff1949b9
    domain: light
    entity_id: light.living_room_floor
    type: turn_off
  - device_id: 8455ac358bbe4b47998c1fba2a51dae4
    domain: light
    entity_id: light.dining_middle
    type: turn_off
