
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Use ui-lovelace.yml to configure the UI
#lovelace:
#  mode: yaml

# Buienradar weather tracker
weather:
  - platform: buienradar
    forecast: true

# Buienradar radar image
camera:
  - platform: buienradar

# Onkyo integration
media_player:
  - platform: onkyo
    host: 10.0.2.1
    name: receiver
    sources:
      tv-cd: TV
      video3: Bluetooth
      video2: T-Mobile
      video6: Steam link
  - platform: philips_js
    host: 10.0.2.22

