
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Editor scenes
scene: !include scenes.yaml
# Manual scenes, split into separate files
scene old: !include_dir_list scenes

# Use ui-lovelace.yml to configure the UI
#lovelace:
#  mode: yaml

# Buienradar weather tracker
weather:
  - platform: buienradar
    forecast: true

# Buienradar radar image
camera:
  - platform: buienradar

# Used to turn on the Philips TV
wake_on_lan:

# Onkyo integration
media_player:
  - platform: onkyo
    host: 10.0.2.1
    name: receiver
    sources:
      cd: TV
      video3: Bluetooth
      video2: T-Mobile
      video6: Steam link
  - platform: philips_js
    host: 10.0.2.22
    name: TV
    api_version: 6
    turn_on_action:
      - service: rest_command.chromecast_boot_tv
      # Old wake-on-lan, does not work with a wired connection (did not try wifi)
      - service: wake_on_lan.send_magic_packet
        data:
          mac: 70:af:24:e5:28:2d

# REST commands
rest_command:
  tv_input:
    url: http://10.0.2.22:1925/6/input/key
    method: POST
    payload: '{"key": "{{ key }}"'
    content_type: 'application/json'
  chromecast_boot_tv:
    url: http://10.0.2.12:8008/apps/ChromeCast
    method: POST

