
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Entity customizations
homeassistant:
  customize:
    person.thijs:
      entity_picture: "/local/thijs.jpg"
    person.frits:
      entity_picture: "/local/frits.jpg"
  packages:
    home_cinema: !include features/home_cinema/definitions.yaml

# Setup SSL
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: https://home.wiefferink.me

# Setup history database (MariaDB addon)
recorder:
  db_url: mysql://homeassistant:n3zhl5kxyeofrgg2yf9pmxtkdv5ubojb6xayvrd68ttgod3szju3qymhti65q9qx@core-mariadb/homeassistant?charset=utf8

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml

# Frontend settings
lovelace:
  # Keep using storage mode for most dashboards
  mode: storage
  dashboards:
    ui-home:
      mode: yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      filename: ui-home.yaml

# Buienradar weather tracker
weather:
  - platform: buienradar
    forecast: true

# Buienradar radar image
camera:
  - platform: buienradar

# Used to turn on the Philips TV
wake_on_lan:

# REST commands
rest_command:
  tv_input:
    url: http://10.0.2.22:1925/6/input/key
    method: POST
    payload: '{"key": "{{ key }}"'
    content_type: 'application/json'
  chromecast_boot_tv:
    url: http://10.0.2.12:8008/apps/ChromeCast
    method: POST

# Light groups
light:
  - platform: group
    name: Living room lights
    entities:
      - light.kitchen_cooking
      - light.kitchen_kielzogschild
      - light.dining_table
      - light.dining_duck
      - light.dining_large_painting
      - light.living_room_iceland_1
      - light.living_room_iceland_2
      - light.living_room_standing
      - light.tv_led_strip
  - platform: group
    name: TV lights
    entities:
      - light.living_room_iceland_1
      - light.living_room_iceland_2
      - light.living_room_standing
      - light.tv_led_strip
  - platform: group
    name: Kitchen lights
    entities:
      - light.kitchen_cooking
      - light.kitchen_kielzogschild
      # Cannot add switch.kitchen_sink to this light group,
      # is linked to light.kitchen_lights using automations
  - platform: group
    name: Dining lights
    entities:
      - light.dining_table
      - light.dining_duck
      - light.dining_large_painting
  - platform: group
    name: "Frits' room lights"
    entities:
      - light.frits_room_wall
      - light.frits_room_cabinet
      - light.frits_room_window

# Machine monitoring
glances:
  # Raspberry Pi itself
  - host: 127.0.0.1
    port: 61209
    name: glances_pi

  # Desktop Thijs
  #- host: 10.0.100.1

# Spotify
spotify:
  client_id: a42ebc5a66854bc3985bd7c08c54eaaa
  client_secret: d56538c409be4f1ba29485293140f7b7
