
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Entity customizations
homeassistant:
  customize:
    person.thijs:
      entity_picture: "/local/thijs.jpg"
    person.frits:
      entity_picture: "/local/frits.jpg"
  packages:
    computer: !include features/computer/definitions.yaml
    gardening: !include features/gardening/definitions.yaml
    home_cinema: !include features/home_cinema/definitions.yaml
    lighting: !include features/lighting/definitions.yaml
    network: !include features/network/definitions.yaml
    presence: !include features/presence/definitions.yaml
    system: !include features/system/definitions.yaml
    weather: !include features/weather/definitions.yaml

# Include themes
frontend:
  themes: !include_dir_merge_named themes

# Enable browser mod (for popups)
browser_mod:
  disable:
    - all

# Setup SSL
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  trusted_proxies:
    # Proxies from wiefferink.me -> wiefferinkhome.ddns.net
    - 178.251.25.134
  use_x_forwarded_for: true

# Setup history database (MariaDB addon)
recorder:
  db_url: mysql://homeassistant:n3zhl5kxyeofrgg2yf9pmxtkdv5ubojb6xayvrd68ttgod3szju3qymhti65q9qx@core-mariadb/homeassistant?charset=utf8
  commit_interval: 5
  exclude:
    entities:
      # Triggers often, no need for history
      - automation.detect_motion_in_the_living_room
      # No need for a long history
      - binary_sensor.motion_living_room
      # Not using history, updates every few seconds while playing
      - media_player.4k
    entity_globs:
      # Change very often, maybe remove completely?
      - sensor.glances_*
  include:
    entities:
      # Showing a graph of this, keep history
      - sensor.glances_cpu_thermal_1_temp
      - sensor.glances_cpu_used_2

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml

# Frontend settings
lovelace:
  # Set the main dashboard to use the yaml configured UI, this is shown as default
  mode: yaml
  resources: !include lovelace_resources.yaml

# REST commands
rest_command:
  tv_input:
    url: http://10.0.2.22:1925/6/input/key
    method: POST
    payload: '{"key": "{{ key }}"'
    content_type: 'application/json'
  chromecast_boot_tv:
    url: http://10.0.2.12:8008/apps/ChromeCast
    method: POST

# Spotify
spotify:
  client_id: a42ebc5a66854bc3985bd7c08c54eaaa
  client_secret: d56538c409be4f1ba29485293140f7b7

# Mailgun email
notify:
  - name: email_thijs
    platform: smtp
    server: smtp.mailgun.org
    port: 587
    timeout: 15
    sender: homeassistant@wiefferink.me
    username: homeassistant@wiefferink.me
    password: 76db3b4c2f93ad140b03980fc2a02380-aa4b0867-8701cba8
    recipient: thijs@wiefferink.me
    sender_name: Home Assistant

# No ip
no_ip:
  domain: wiefferinkhome.ddns.net
  username: thijs-noip@wiefferink.me
  password: jm1o21w9yk2n7lg5223r87usho9l3ym3kiaavkeyvwz6o2fp26r5cieijq10qjxb
