custom_header:
  compact_mode: true
  footer_mode: true
  menu_hide: true
  reverse_button_direction: true
  reverse_tab_direction: true
title: 'Home'
views:
  - badges: []
    cards:
      - !include ui/lights/livingroom.yaml
      - !include features/home_cinema/ui/mode-select.yaml
      - !include features/home_cinema/ui/players.yaml
      - !include features/home_cinema/ui/mode-select-2.yaml
      #- !include ui/media/plex-status.yaml, not useful yet

    icon: 'mdi:theater'
    path: living-room
    title: ''
  - badges:
      - entity: person.thijs
      - entity: person.frits
      - entity: sun.sun
    cards:
      - entities:
          - entity: device_tracker.gm1913
          - entity: device_tracker.iphone_frits
        hours_to_show: 24
        refresh_interval: 0
        title: Who was home?
        type: history-graph
      - cards:
          - aspect_ratio: 80%
            type: iframe
            url: >-
              https://www.buienalarm.nl/amsterdam-noord-holland-nederland/52.3161,4.9651
          - entity: weather.br_unknown_station
            name: Buienradar
            type: weather-forecast
        type: vertical-stack
      - aspect_ratio: 100%
        camera_image: camera.buienradar_loop
        camera_view: live
        entity: camera.buienradar_loop
        hold_action:
          action: none
        name: Buienradar
        show_name: false
        show_state: false
        tap_action:
          action: none
        type: picture-entity
      - cards:
          - entities:
              - entity: sensor.netherlands_coronavirus_confirmed
                name: Confirmed
                show_fill: false
              - entity: sensor.netherlands_coronavirus_current
                name: Current
                show_fill: false
              - entity: sensor.netherlands_coronavirus_recovered
                name: Recovered
                show_fill: false
              - entity: sensor.netherlands_coronavirus_deaths
                name: Deaths
                show_fill: false
            height: 200
            hour24: true
            hours_to_show: 336
            icon: 'mdi:thermometer'
            line_color:
              - '#0087c7'
              - orange
              - green
              - red
            lower_bound: 0
            name: Corona The Netherlands
            points_per_hour: 0.2
            show:
              labels: true
            type: 'custom:mini-graph-card'
          - entities:
              - entity: sensor.worldwide_coronavirus_confirmed
                name: Confirmed
                show_fill: false
              - entity: sensor.worldwide_coronavirus_current
                name: Current
                show_fill: false
              - entity: sensor.worldwide_coronavirus_recovered
                name: Recovered
                show_fill: false
              - entity: sensor.worldwide_coronavirus_deaths
                name: Deaths
                show_fill: false
            height: 200
            hour24: true
            hours_to_show: 336
            icon: 'mdi:thermometer'
            line_color:
              - '#0087c7'
              - orange
              - green
              - red
            lower_bound: 0
            name: Corona Worldwide
            points_per_hour: 0.2
            show:
              labels: true
            type: 'custom:mini-graph-card'
        type: vertical-stack
    icon: 'mdi:home'
    panel: false
    path: default_view
    title: ''
  - badges: []
    cards:
      - entity: light.ceiling_thijs
        icon: 'mdi:rectangle-outline'
        name: Light
        type: light
      - entities:
          - entity: media_player.bedroom_speaker
            group: true
            icon: 'mdi:google-home'
            name: Google Home Mini
            tts:
              platform: google_translate
            type: 'custom:mini-media-player'
          - entity: sensor.battery_level
          - entity: device_tracker.gm1913
          - entity: sensor.wifi_connection
        type: entities
      - entity: media_player.spotify_thijs
        type: media-control
      - client_id: a42ebc5a66854bc3985bd7c08c54eaaa
        type: 'custom:spotify-card'
    icon: ''
    path: thijs
    title: Thijs
  - badges: []
    cards:
      - entities:
          - entities:
              - entity: light.frits_room_wall
                icon: 'mdi:image-size-select-actual'
                name: Wall
              - entity: light.frits_room_cabinet
                icon: 'mdi:wardrobe'
                name: Cabinet
              - entity: light.frits_room_window
                icon: 'mdi:window-closed-variant'
                name: Window
            group_config:
              type: 'custom:slider-entity-row'
            head:
              entity: light.frits_room_lights
              icon: 'mdi:track-light'
              name: Ceiling
              state_color: false
              type: 'custom:slider-entity-row'
            open: false
            type: 'custom:fold-entity-row'
        show_header_toggle: false
        title: Lights
        type: entities
      - entities:
          - sensor.bssid
          - sensor.battery_level_2
          - sensor.battery_state
          - sensor.connection_type
          - sensor.geocoded_location
          - sensor.last_update_trigger
          - device_tracker.iphone_frits
          - sensor.sim_1
          - sensor.ssid
        type: entities
    path: frits
    title: Frits
  - badges: []
    cards:
      - entities:
          - entities:
              - entity: light.tv_lights
                icon: 'mdi:television'
                name: TV
                state_color: false
                type: 'custom:slider-entity-row'
              - entity: light.dining_lights
                icon: 'mdi:table-chair'
                name: Dining
                state_color: false
                type: 'custom:slider-entity-row'
              - entity: light.kitchen_lights
                icon: 'mdi:chef-hat'
                name: Kitchen
                state_color: false
                type: 'custom:slider-entity-row'
            head:
              entity: light.living_room_lights
              name: Living room
              state_color: false
              type: 'custom:slider-entity-row'
            type: 'custom:fold-entity-row'
          - entities:
              - entity: sensor.toilet_motion_sensor
                icon: 'mdi:motion-sensor'
                name: Motion sensor
            head:
              entity: light.toilet
              icon: 'mdi:toilet'
              state_color: false
              type: 'custom:slider-entity-row'
            type: 'custom:fold-entity-row'
          - entities:
              - entity: sensor.hall_ground_floor_motion_sensor
                icon: 'mdi:motion-sensor'
                name: Motion sensor
            head:
              entity: light.ground_floor_hall
              icon: 'mdi:road'
              name: Hall
              state_color: false
              type: 'custom:slider-entity-row'
            type: 'custom:fold-entity-row'
          - entities:
              - entity: sensor.closet_motion_sensor
                icon: 'mdi:motion-sensor'
                name: Motion sensor
            head:
              entity: light.closet
              icon: 'mdi:wardrobe'
              name: Closet
              state_color: false
              type: 'custom:slider-entity-row'
            type: 'custom:fold-entity-row'
        show_header_toggle: false
        title: Ground floor
        type: entities
      - entities:
          - entities:
              - entity: sensor.first_floor_motion_sensor
                icon: 'mdi:motion-sensor'
                name: Motion sensor
            head:
              entity: light.hall_first_floor
              icon: 'mdi:road'
              name: Hall
              state_color: false
              type: 'custom:slider-entity-row'
            type: 'custom:fold-entity-row'
          - entities:
              - entity: light.frits_room_wall
                icon: 'mdi:image-size-select-actual'
                name: Wall
              - entity: light.frits_room_cabinet
                icon: 'mdi:wardrobe'
                name: Cabinet
              - entity: light.frits_room_window
                icon: 'mdi:window-closed-variant'
                name: Window
            group_config:
              type: 'custom:slider-entity-row'
            head:
              entity: light.frits_room_lights
              icon: 'mdi:track-light'
              name: Frits' room
              state_color: false
              type: 'custom:slider-entity-row'
            open: false
            type: 'custom:fold-entity-row'
          - entities:
              - entity: sensor.remote_thijs
                icon: 'mdi:remote-tv'
                name: Remote
            head:
              entity: light.ceiling_thijs
              icon: 'mdi:rectangle-outline'
              name: Thijs' room
              state_color: false
              type: 'custom:slider-entity-row'
            type: 'custom:fold-entity-row'
          - entities:
              - entity: sensor.remote_computers
                icon: 'mdi:remote-tv'
                name: Remote
            head:
              entity: light.ceiling_computers
              icon: 'mdi:desktop-tower-monitor'
              name: Computers
              state_color: false
              type: 'custom:slider-entity-row'
            type: 'custom:fold-entity-row'
        show_header_toggle: false
        title: First floor
        type: entities
      - entities:
          - entities:
              - entity: sensor.motion_sensor_attic_hall
                icon: 'mdi:motion-sensor'
                name: Motion sensor
            head:
              entity: light.attic_hall
              icon: 'mdi:washing-machine'
              name: Washing hall
              state_color: false
              type: 'custom:slider-entity-row'
            type: 'custom:fold-entity-row'
          - entities:
              - entity: sensor.attic_motion_sensor
                icon: 'mdi:motion-sensor'
                name: Motion sensor
            head:
              entity: switch.standing_lamp
              icon: 'mdi:floor-lamp'
              name: Standing lamp
              state_color: false
            type: 'custom:fold-entity-row'
        show_header_toggle: false
        title: Second floor
        type: entities
    icon: 'mdi:lightbulb'
    path: lights
