title: 'Home'
custom_header:
  compact_mode: true
  footer_mode: false
  menu_hide: true
  reverse_button_direction: true
  reverse_tab_direction: true
views:

  # Living room
  - icon: 'mdi:theater'
    path: living-room
    badges:
      - entity: person.thijs
      - entity: person.frits
    cards:
      - !include features/lighting/ui/living_room.yaml
      - !include features/home_cinema/ui/mode-select.yaml
      - !include features/home_cinema/ui/players.yaml
      #- !include ui/media/plex-status.yaml, not useful yet
      - type: horizontal-stack
        cards:
          - !include features/weather/ui/summary_living_room.yaml
          - !include features/weather/ui/summary_garden.yaml
      - !include features/weather/ui/forecast.yaml
      - !include features/weather/ui/buienradar.yaml
      - !include features/weather/ui/buienalarm.yaml

  # Stats
  - icon: mdi:trending-up
    path: stats
    cards:
      - entities:
          - entity: device_tracker.gm1913
          - entity: device_tracker.iphone_frits
        hours_to_show: 24
        refresh_interval: 0
        title: Who was home?
        type: history-graph
      - type: vertical-stack
        cards:
          - !include ui/covid_19/netherlands.yaml
          - !include ui/covid_19/world.yaml

  # Thijs
  - title: Thijs
    path: thijs
    badges: []
    cards:
      - !include features/lighting/ui/room_thijs.yaml
      - entities:
          - entity: media_player.bedroom_speaker
            group: true
            icon: 'mdi:google-home'
            name: Google Home Mini
            tts:
              platform: google_translate
            type: 'custom:mini-media-player'
          - entity: sensor.battery_phone_thijs
          - entity: device_tracker.gm1913
          - entity: sensor.wifi_connection
        type: entities
      - entity: media_player.spotify_thijs
        type: media-control
      # TODO fix redirect url for new dashboard path (and think about what this card should do)
      #- client_id: a42ebc5a66854bc3985bd7c08c54eaaa
      #  type: 'custom:spotify-card'

  # Frits
  - title: Frits
    path: frits
    badges: []
    cards:
      - !include features/lighting/ui/room_frits.yaml
      - entities:
          - sensor.bssid
          - sensor.battery_iphone_frits
          - sensor.battery_state
          - sensor.connection_type
          - sensor.geocoded_location
          - sensor.last_update_trigger
          - device_tracker.iphone_frits
          - sensor.sim_1
          - sensor.ssid
        type: entities

  # Plants
  - icon: mdi:sprout
    path: plants
    cards:
      - !include features/gardening/ui/plant.yaml

  # Lighting
  - icon: mdi:lightbulb
    path: lights
    badges: []
    cards:
      - !include features/lighting/ui/floor_0.yaml
      - !include features/lighting/ui/floor_1.yaml
      - !include features/lighting/ui/floor_2.yaml

# Templates for type:custom-button
button_card_templates:
  header:
    styles:
      card:
        - padding: 24px 16px 8px 16px
      name:
        - justify-self: start
        - font-size: 24px
      label:
        - justify-self: start
