automation: !include_dir_merge_list automations


# Script for changing between modes
script:
  living_room_lighting_mode: !include scripts/set_living_room_lighting_mode.yaml


# Setup all light icons
homeassistant:
  customize:
    ##### Ground floor
    # TV
    light.living_room_iceland_1:
      icon: mdi:track-light
    light.living_room_iceland_2:
      icon: mdi:track-light
    light.living_room_standing:
      icon: mdi:floor-lamp
    light.tv_led_strip:
      icon: mdi:led-strip-variant
    # Dining
    light.dining_duck:
      icon: mdi:track-light
    light.dining_large_painting:
      icon: mdi:track-light
    light.dining_table:
      icon: mdi:track-light
    # Kitchen
    light.kitchen_cooking:
      icon: mdi:track-light
    light.kitchen_kielzogschild:
      icon: mdi:track-light
    switch.kitchen_sink:
      icon: mdi:water-pump
    # Toilet
    light.toilet:
      icon: mdi:toilet
    # Closet
    light.closet:
      icon: mdi:wardrobe
    # Hall
    light.ground_floor_hall:
      icon: mdi:road

    ##### First floor
    # Thijs' room
    light.bedroom_thijs_ceiling:
      icon: mdi:rectangle-outline
    # Frits' room
    light.frits_room_cabinet:
      icon: mdi:wardrobe
    light.frits_room_wall:
      icon: mdi:image-size-select-actual
    light.frits_room_window:
      icon: mdi:window-closed-variant
    # Hall
    light.hall_first_floor:
      icon: mdi:road
    # Computer room
    light.computers_ceiling:
      icon: mdi:desktop-tower-monitor

    ##### Second floor
    # Hall
    light.attic_hall:
      icon: mdi:washing-machine
    # Room
    switch.standing_lamp:
      icon: mdi:floor-lamp

  customize_glob:
    # Motion sensors
    "sensor.motion_*":
      icon: mdi:motion-sensor
    # Remotes
    "sensor.remote_*":
      icon: mdi:remote-tv


# Light groups
# Note: for some reason these don't support an 'icon' prop, hopefully in newer versions though
light:
  # Lights in the complete living room (light.living_room_lights)
  - platform: group
    name: Living room lights
    entities:
      - light.kitchen_cooking
      - light.kitchen_kielzogschild
      - light.dining_table
      - light.dining_duck
      - light.dining_large_painting
      - light.living_room_iceland_1
      - light.living_room_iceland_2
      - light.living_room_standing
      - light.tv_led_strip
  # Lights around the TV (light.tv_lights)
  - platform: group
    name: TV lights
    entities:
      - light.living_room_iceland_1
      - light.living_room_iceland_2
      - light.living_room_standing
      - light.tv_led_strip
  # Kitchen lights (light.kitchen_lights)
  - platform: group
    name: Kitchen lights
    entities:
      - light.kitchen_cooking
      - light.kitchen_kielzogschild
      # Cannot add switch.kitchen_sink to this light group,
      # is linked to light.kitchen_lights using automations
  # Lights for dining
  - platform: group
    name: Dining lights
    entities:
      - light.dining_table
      - light.dining_duck
      - light.dining_large_painting
  # Lights in Frits' room (light.frits_room_lights)
  - platform: group
    name: "Frits' room lights"
    entities:
      - light.frits_room_wall
      - light.frits_room_cabinet
      - light.frits_room_window
  # Lights in Thijs' room (light.thijs_room_lights)
  - platform: group
    name: "Thijs' room lights"
    entities:
      - light.bedroom_thijs_ceiling
      - light.bedroom_thijs_bed


input_select:
  # Living room light mode: determines brightness of all lights
  living_room_lighting_mode:
    name: Living room lighting mode
    icon: mdi:brightness-4
    options:
      - 'manual'
      - 'day'
      - 'cooking'
      - 'evening'
      - 'night'


# A smoothed value for the light intensity in the living room
sensor:
  - platform: filter
    name: "Living room light level (smoothed)"
    entity_id: sensor.living_room_light_level
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
      - filter: lowpass
        time_constant: 10
      - filter: time_simple_moving_average
        window_size: "00:03"
        precision: 2
