# Turn off
- alias: Turn off the computer room lights when the computers are off
  trigger:
    - platform: state
      entity_id: device_tracker.computer_thijs
      to: 'not_home'
    - platform: state
      entity_id: device_tracker.computer_frits
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.computer_thijs
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.computer_frits
      state: 'not_home'
  action:
    - service: light.turn_off
      data:
        entity_id: light.ceiling_computers

# Turn on
- alias: Turn on the computer room lights when a computer turns on
  trigger:
    - platform: state
      entity_id: device_tracker.computer_thijs
      to: home
    - platform: state
      entity_id: device_tracker.computer_frits
      to: home
  action:
    - service: light.turn_on
      data:
        entity_id: light.ceiling_computers
