# Computer room light automation

# Turn off
- alias: Turn off the computer room lights when there are no computers/laptops on
  trigger:
    - platform: state
      entity_id: binary_sensor.computer_room_used_devices
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.computers_ceiling

# Turn on
- alias: Turn on the computer room lights when a computer/laptop is on
  trigger:
    - platform: state
      entity_id: binary_sensor.computer_room_used_devices
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.computers_ceiling

# Brightness and color temperature control when turned on
- alias: Computer room light starts dimmed when turned on at night
  trigger:
    - entity_id: light.computers_ceiling
      platform: state
      to: 'on'
    - platform: time
      at: "18:00:00"
    - platform: time
      at: "8:00:01"
  condition:
    - condition: state
      entity_id: light.computers_ceiling
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.computers_ceiling
        brightness_pct: >-
          {% if now().hour >= 19 or now().hour <= 8 %}
            50
          {% else %}
            100
          {% endif %}
        # White during the day, yellow-ish at night
        color_temp: >-
          {% if now().hour >= 18 or now().hour <= 8 %}
            370
          {% else %}
            250
          {% endif %}
