 # First floor hall
- alias: First floor hall light starts dimmed when turned on at night
  trigger:
    - entity_id: light.hall_first_floor
      platform: state
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hall_first_floor
        brightness: >-
          {% if is_state('sun.sun', 'below_horizon') %}
            1
          {% else %}
            255
          {% endif %}

