# Turn on the lights when there is motion
- alias: "Hall ground floor turn on when there is motion"
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_ground_floor_motion_sensor
      to: 'on'
  action:
    # Turn on the light
    - service: light.turn_on
      data:
        entity_id: light.hall_ground_floor

    # Wait until there is no motion anymore
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.hall_ground_floor_motion_sensor
        to: 'off'

    # Turn off the light
    - service: light.turn_off
      data:
        entity_id: light.hall_ground_floor
        transition: 5

# Dimmed when turned on at night
- alias: Ground floor hall light starts dimmed when turned on at night
  trigger:
    - entity_id: light.ground_floor_hall
      platform: state
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.ground_floor_hall
        brightness_pct: >-
          {% if is_state('sun.sun', 'below_horizon') %}
            20
          {% else %}
            100
          {% endif %}