# Automate living room lights

- alias: Turn off the living room lights when we are both upstairs
  trigger:
    - platform: template
      value_template: "{% if not is_state_attr('device_tracker.phone_thijs', 'ap_mac', '18:e8:29:90:42:42') %}true{% endif %}"
    - platform: template
      value_template: "{% if not is_state_attr('device_tracker.phone_frits', 'ap_mac', '18:e8:29:90:42:42') %}true{% endif %}"
  condition:
    condition: and
    conditions:
      # Frits is not downstairs
      - condition: template
        value_template: "{{ not is_state_attr('device_tracker.phone_frits', 'ap_mac', '18:e8:29:90:42:42') }}"
      # Thijs is not downstairs
      - condition: template
        value_template: "{{ not is_state_attr('device_tracker.phone_thijs', 'ap_mac', '18:e8:29:90:42:42') }}"
  action:
    - service_template: >-
        {% if is_state_attr('device_tracker.phone_thijs', 'ap_mac', '18:e8:29:90:42:42') or is_state_attr('device_tracker.phone_frits', 'ap_mac', '18:e8:29:90:42:42') %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      data:
        entity_id: light.living_room_lights

- alias: Turn on the living room lights when at least one of us is downstairs
  trigger:
    # One of us moves to downstairs
    - platform: template
      value_template: "{% if is_state_attr('device_tracker.phone_thijs', 'ap_mac', '18:e8:29:90:42:42') %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('device_tracker.phone_frits', 'ap_mac', '18:e8:29:90:42:42') %}true{% endif %}"
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room_lights
