# Automate living room lights

# Turn on based on presence
- alias: Turn off the living room lights when we are both upstairs
  trigger:
    - platform: template
      value_template: "{% if not is_state_attr('device_tracker.phone_thijs', 'ap_mac', '18:e8:29:90:42:42') %}true{% endif %}"
    - platform: template
      value_template: "{% if not is_state_attr('device_tracker.phone_frits', 'ap_mac', '18:e8:29:90:42:42') %}true{% endif %}"
  condition:
    condition: and
    conditions:
      # Frits is not downstairs
      - condition: template
        value_template: "{{ not is_state_attr('device_tracker.phone_frits', 'ap_mac', '18:e8:29:90:42:42') }}"
      # Thijs is not downstairs
      - condition: template
        value_template: "{{ not is_state_attr('device_tracker.phone_thijs', 'ap_mac', '18:e8:29:90:42:42') }}"
  action:
    - service_template: >-
        {% if is_state_attr('device_tracker.phone_thijs', 'ap_mac', '18:e8:29:90:42:42') or is_state_attr('device_tracker.phone_frits', 'ap_mac', '18:e8:29:90:42:42') %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      data:
        entity_id: light.living_room_lights

# Turn off based on presence
- alias: Turn on the living room lights when at least one of us is downstairs
  trigger:
    # One of us moves to downstairs
    - platform: template
      value_template: "{% if is_state_attr('device_tracker.phone_thijs', 'ap_mac', '18:e8:29:90:42:42') %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('device_tracker.phone_frits', 'ap_mac', '18:e8:29:90:42:42') %}true{% endif %}"
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room_lights

# Set brightness automatically
- alias: Living room lights turn on brightness
  trigger:
    - entity_id: light.living_room_lights
      platform: state
      to: 'on'
    - platform: time
      at: "18:00:00"
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.living_room_lights
        brightness_pct: >-
          {% if now().hour >= 18 or now().hour <= 8 %}
            40
          {% else %}
            100
          {% endif %}
