# Track presence of people in the living room
# TODO move into separate module? (and computer room tracking as well?)

# Turn off when both not downstairs
- alias: Detect phones leaving the living room
  trigger:
    - platform: template
      value_template: "{% if not is_state_attr('device_tracker.phone_thijs', 'ap_mac', '18:e8:29:90:42:42') %}true{% endif %}"
    - platform: template
      value_template: "{% if not is_state_attr('device_tracker.phone_frits', 'ap_mac', '18:e8:29:90:42:42') %}true{% endif %}"
  condition:
    condition: and
    conditions:
      # Frits is not downstairs
      - condition: template
        value_template: "{{ not is_state_attr('device_tracker.phone_frits', 'ap_mac', '18:e8:29:90:42:42') }}"
      # Thijs is not downstairs
      - condition: template
        value_template: "{{ not is_state_attr('device_tracker.phone_thijs', 'ap_mac', '18:e8:29:90:42:42') }}"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.living_room_in_use

# Turn on when one of us is downstairs
- alias: Detect a phone present in the living room
  trigger:
    # One of us moves to downstairs
    - platform: template
      value_template: "{% if is_state_attr('device_tracker.phone_thijs', 'ap_mac', '18:e8:29:90:42:42') %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state_attr('device_tracker.phone_frits', 'ap_mac', '18:e8:29:90:42:42') %}true{% endif %}"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.living_room_in_use

# Turn on when there is movement
# TODO use the motion sensor
#- alias: Detect movement in the living room
#  trigger:
#    - platform: template
#
