# Link the sink lights to match the kitchen lights based on brightness
- alias: Kitchen - Turn on the sink light based on the kitchen lights
  trigger:
    - above: 100
      entity_id: light.kitchen_lights
      platform: numeric_state
      value_template: '{{ state.attributes.brightness }}'
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_sink
- alias: Kitchen - Turn off the sink light based on the kitchen lights
  trigger:
    - below: 100
      entity_id: light.kitchen_lights
      platform: numeric_state
      value_template: '{{ state.attributes.brightness }}'
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_sink
