 # Thijs' room lights turn on brightness
- alias: "Thijs' room lights turn on dimmed at night"
  trigger:
    - entity_id: light.bedroom_thijs_ceiling
      platform: state
      to: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_thijs_ceiling
        # Future: declare this condition once in a variable (HA 0.115+)
        # Full bright during the day, dimmed at night
        brightness: >-
          {% if now().hour >= 18 or (now().hour <= 12 and is_state('sun.sun', 'below_horizon')) %}
            1
          {% else %}
            255
          {% endif %}
        # Warm white during night, bright white during the day
        color_temp: >-
          {% if now().hour >= 18 or (now().hour <= 12 and is_state('sun.sun', 'below_horizon')) %}
            500
          {% else %}
            250
          {% endif %}

# Turn off the light when going downstairs
- alias: "Thijs' room turn off when going downstairs"
  trigger:
    - entity_id: sensor.phone_thijs_wifi_ap
      platform: state
      from: 'upstairs'
  action:
    - service: light.turn_off
      data_template:
        entity_id: light.thijs_room_lights

# Update lighting when changing do-not-disturb
- alias: "Thijs' room turn off when going into do-not-disturb"
  trigger:
    - platform: state
      entity_id: sensor.phone_thijs_do_not_disturb
      to: 'priority_only'
  action:
    - service: light.turn_off
      data:
        entity_id: light.thijs_room_lights
        transition: 10

- alias: "Thijs' room turn on when going out of do-not-disturb"
  trigger:
    - platform: state
      entity_id: sensor.phone_thijs_do_not_disturb
      to: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.thijs_room_lights
        transition: 10

# Turn on the lights when there is motion
- alias: "Thijs' room turn on when there is motion"
  trigger:
     - type: occupied
       device_id: 398f682c8f2f475185dea14e8c6b89a7
       domain: binary_sensor
       entity_id: binary_sensor.thijs_room_motion_sensor_occupancy
       platform: device
  action:
    # Just the led strip for now, also do ceiling depending on the time though
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_thijs_bed
        brightness: >-
          {% if now().hour >= 18 or (now().hour <= 12 and is_state('sun.sun', 'below_horizon')) %}
            50
          {% else %}
            255
          {% endif %}
        color_temp: >-
          {% if now().hour >= 18 or (now().hour <= 12 and is_state('sun.sun', 'below_horizon')) %}
            495
          {% else %}
            300
          {% endif %}


 # NFC tag test
- alias: "Light based on NFC tag"
  trigger:
    - platform: event
      event_type: tag_scanned
      event_data:
        device_id: 12945536d161848a
        tag_id: a5d1420c-898c-4f29-85f5-57a12f6e0868
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_thijs_ceiling
        brightness_pct: 50
        color_temp: 250 # Bright white
    # Debugging
    - service: notify.mobile_app_phone_thijs
      data_template:
        message: NFC tag scanned!
        data:
          tag: nfc
