- alias: LetsEncrypt certificate renewal for wiefferinkhome.ddns.net
  trigger:
    - platform: time
      # An hour before the daily restart
      at: '04:00:00'
  condition:
    - condition: time
      weekday:
        - sat
  action:
    - service: hassio.addon_start
      data:
        addon: core_letsencrypt
