# Detect pending for too long, assume something failed
alias: Detect too long pending state
trigger:
  - entity_id: input_boolean.home_cinema_pending
    platform: state
    to: 'on'
action:
  # When pending for more than 15 seconds
  - delay: 00:00:15
  # Reset pending (allows trying again)
  - condition: state
    entity_id: input_boolean.home_cinema_pending
    state: 'on'
  - entity_id: input_boolean.home_cinema_pending
    service: input_boolean.turn_off
  # Notify phone of Thijs
  - service: notify.mobile_app_phone_thijs
    data_template:
      message: >-
        Setting home cinema to {{ states("input_select.home_cinema_mode") }} failed, still pending after 15 seconds!
      data:
        tag: battery
