alias: Home cinema mode to off
trigger:
  # TV turns off
  - platform: "state"
    entity_id: "media_player.hdmi_0"
    to: "off"
  # Receiver turns off
  - platform: "state"
    entity_id: "media_player.hdmi_5"
    to: "off"
condition:
  # TV is off
  - condition: "state"
    entity_id: "media_player.hdmi_0"
    state: "off"
  # Receiver is off
  - condition: "state"
    entity_id: "media_player.hdmi_5"
    state: "off"
action:
  # Update the mode
  - service: input_select.select_option
    data_template:
      entity_id: input_select.home_cinema_mode
      option: "off"
  - service: "input_boolean.turn_off"
    data:
      entity_id: "input_boolean.home_cinema_pending"
  # Turn off the Chromecast (in case this is a manual turn off tv)
  - service: "media_player.turn_off"
    data:
      entity_id: "media_player.4k"
  # Turn off the LED strip
  - service: light.turn_off
    data:
      entity_id: light.tv_led_strip
      transition: 5
