alias: Home cinema mode to ChromeCast (by checking receiver state)
trigger:
  # Receiver changes source or state
  - platform: "state"
    entity_id: "media_player.receiver"
condition:
  # Receiver is on
  - condition: "state"
    entity_id: "media_player.receiver"
    state: "on"
  # Receiver is on the T-Mobile input
  - condition: "template"
    value_template: "{{is_state_attr('media_player.receiver', 'source', 'T-Mobile')}}"
action:
  # Update the mode
  - service: input_select.select_option
    data:
      entity_id: input_select.home_cinema_mode
      option: "tv"
  - service: "input_boolean.turn_off"
    data:
      entity_id: "input_boolean.home_cinema_pending"
  # LED strip to purple
  - service: light.turn_on
    entity_id: light.tv_led_strip
    data:
      brightness: 254
      rgb_color:
        - 255
        - 46
        - 129
