# System maintenance and monitoring

automation: !include_dir_merge_list automations

binary_sensor:
  # Indicates if there are any HA or HACS updates
  # Note: only required because the conditional card does not have 'or' conditions
  - platform: template
    sensors:
      updates_available:
        friendly_name: "Updates available"
        value_template: "{{ is_state('binary_sensor.updater', 'on') or states('sensor.hacs') > 0 }}"
