- alias: CO2 in the computer room is getting high
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_computers_co2
      above: '800'
    # Repeat when getting to 1100
    - platform: numeric_state
      entity_id: sensor.netatmo_computers_co2
      above: '1100'
  action:
    - service: script.computer_thijs_notify
      data:
        title: The CO2 level is at {{states("sensor.netatmo_computers_co2")}} ppm!
        message: Open a window to fix it
    # Flash the lights
    - repeat:
        count: 6
        sequence:
          - delay: 1
          - service: light.toggle
            data:
              entity_id: light.computers_ceiling
