# Weather tracking components and UI

# Buienradar weather tracker
weather:
  - platform: buienradar
    forecast: true
    name: buienradar_home

# Buienradar radar image
camera:
  - platform: buienradar
    dimension: 700
    name: buienradar_home

# Night sensor to use in graphs
binary_sensor:
  - platform: tod
    name: Night
    after: sunset
    before: sunrise
  - platform: tod
    name: Day
    after: sunrise
    before: sunset
