# Weather tracking components and UI

automation: !include_dir_merge_list automations

# Night sensor to use in graphs
binary_sensor:
  - platform: tod
    name: Night
    after: sunset
    before: sunrise
  - platform: tod
    name: Day
    after: sunrise
    before: sunset

# Sensor for the elevation of the sun
sensor:
  - platform: template
    sensors:
      solar_elevation:
        friendly_name: "Sun elevation"
        unit_of_measurement: '°'
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
