name: "Check the configuration"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    name: Home Assistant configuration check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Check the current stable version and the latest dev version
        # - mostly likely I'm running stable, so that should work
        # - running on DEV to spot problems before I update
        HA_VERSION: [STABLE, DEV]
      max-parallel: 2
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Config Check
        uses: ludeeus/action-ha-config-check@master
        with:
          version: matrix.HA_VERSION
